# Generated by Django 4.0.4 on 2022-05-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='blog summary', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
