# Generated by Django 4.0.4 on 2022-04-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orderitem_delete_orderline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address1',
            new_name='billing_address',
        ),
    ]
