# Generated by Django 4.0.4 on 2022-05-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_billing_address1_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address1',
            new_name='shipping_address',
        ),
    ]
